### ISSUE TITLE
FireBladeConfUtil fails on createPodConfFiles on Windows

### ISSUE THREAD

**Issue by denissignoretto** [Firelay/blade-openshift-extension#2]
It should use always use SystemUtils.FILE_SEPARATOR

**Comment by SafPlusPlus** [comment]
Should be fixed with commit https://github.com/Firelay/blade-openshift-extension/commit/86b4994294c5e2fd034307a0c8718c0a03e0d67b.

Thanks for reporting the issue and please reopen if you find somewhere where the system independent file separator was missed.
